### ISSUE TITLE
My account was deactivated again!!

### ISSUE THREAD

**Issue by terion-name** [JeffreyWay/Laracasts-Bugs#98]
My account was deactivated early (see #94), 15 days ago I've updated card info and reactivated it (money was withdrawed), now I open laracasts and see, that I was deactivated again!
WTF?

**Comment by terion-name** [comment]
Have a look at billing history:
https://www.evernote.com/shard/s159/sh/b8f83bf0-4ed2-4e7e-8271-ff0b910ecdf0/ef7feb7746705f4575b85b7f79ded01b

My account was earlier deactivated in first days of March (that was #94 about)
And then, at 9th March I've updated billing info, account was reactivated and monthly fee was withdrawed. But this is not displayed in payment history! And now it says, that March 17 is unpaid!

**Comment by laracasts** [comment]
My billing provider is showing that you started a new billing period on March 17th, however, again, your card was declined. Because your subscription is past due, your account was deactivated.

It looks like the March 9th payment covered the payment that was due on February 17th, so that is where it was logged. It's now trying to invoice for the March 17th payment, but the card is being declined.

**Comment by terion-name** [comment]
Hmmm... You mean that Feb. 17th wasn't payed in due? Wierd...
